"""add avatar_hash column

Revision ID: c747b0b5d8ce
Revises: a17a86b14f92
Create Date: 2016-04-01 09:39:50.236000

"""

# revision identifiers, used by Alembic.
revision = 'c747b0b5d8ce'
down_revision = 'a17a86b14f92'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_hash', sa.String(length=32), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_hash')
    ### end Alembic commands ###
